# This is a basic workflow to help you get started with Actions

name: Linux CI

env:
  MODULE_PREFIX: third_party/module

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_typr: [Debug, Release]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Show enviroments
        run: |
          pwd
          ls -l
          mkdir -p "$MODULE_PREFIX"

      - name: Install tools
        run: |
          git clone https://github.com/fmtlib/fmt.git -b 7.1.3 --depth 1
          cd fmt
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ..
          make -j
          make install

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
