name: macOS

# Controls when the action will run.
on:
  # Triggers the workflow on events but only for branches.
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on

    strategy:
      matrix:
        os: [macos-latest]
        build_type: [Debug, Release]
        cxx: [clang++]
        cxxstd: [20]

    runs-on: ${{matrix.os}}
    env:
      CXX: ${{matrix.cxx}}
      FMT_SRC_DIR: ${{github.workspace}}/third_party/fmt
      SPDLOG_SRC_DIR: ${{github.workspace}}/third_party/spdlog
      MODULE_PREFIX: ${{github.workspace}}/third_party/module

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup packages
        run: |
          brew update
          brew install ninja gmp googletest

      - name: Download libfmt
        run: |
          git clone https://github.com/fmtlib/fmt.git -b 7.1.3 --depth 1 $FMT_SRC_DIR
          cmake -E make_directory $FMT_SRC_DIR/build

      - name: Download libspdlog
        run: |
          git clone https://github.com/gabime/spdlog.git -b v1.8.2 --depth 1 $SPDLOG_SRC_DIR
          cmake -E make_directory $SPDLOG_SRC_DIR/build
